#!/bin/sh

# Get the original cernlib sources

tar -zxvf $CERN/cernlib_2005.tgz > cernlib_2005_orig.lst

# Unpack the source files and set up the build structure in $CERN

list=`ls src_*.gz`

for ffile in $list
do
  gunzip -c $ffile | tar xf -
done

# Overload corrections to cernlib 2005

tar -zxvf $CERN/cernlib.2005.corr.tgz > cernlib_corr.lst

# Make sure that "kuip" uses its own "strndup" version

sed -i -e '{s/strndup/Strndup/g}' \
  ./2005/src/packlib/kuip/code_kuip/kalias.c \
  ./2005/src/packlib/kuip/code_kuip/kbrow.c \
  ./2005/src/packlib/kuip/code_kuip/kedit.c \
  ./2005/src/packlib/kuip/code_kuip/kexec.c \
  ./2005/src/packlib/kuip/code_kuip/kkern.c \
  ./2005/src/packlib/kuip/code_kuip/kmacro.c \
  ./2005/src/packlib/kuip/code_kuip/kmath.c \
  ./2005/src/packlib/kuip/code_kuip/kmenu.c \
  ./2005/src/packlib/kuip/code_motif/kmfile.c \
  ./2005/src/packlib/kuip/kuip/kstring.h \
  ./2005/src/packlib/kuip/ykuip/kmath.y

