#!/bin/sh

# The cernlib environment

CERN=`pwd`
CERN_ROOT=$CERN/$CERN_LEVEL
CVSCOSRC=$CERN/$CERN_LEVEL/src
PATH=$CERN_ROOT/bin:$PATH

export CERN
export CERN_LEVEL
export CERN_ROOT 
export CVSCOSRC
export PATH


# get the log file name of start_cern
cd $CERN_ROOT/build/log
logfile=`ls | grep "make\."`

# install the executables
cd $CERN_ROOT/build/pawlib
gmake  install.bin >> ../log/$logfile 2>&1
cd $CERN_ROOT/build/packlib
gmake  install.bin >> ../log/$logfile 2>&1

cd $CERN

